name: Build and lint services

on: [push]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build wallet frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./src/wallet/frontend
          file: ./src/wallet/frontend/Dockerfile

      - name: Lint backend
        run: uvx flake8 ./src/wallet/backend/src --show-source --statistics

      - name: Build wallet backend image
        uses: docker/build-push-action@v6
        with:
          context: ./src/wallet/backend
          file: ./src/wallet/backend/Dockerfile
