name: Build and lint services

on: [push]

jobs:
  build-docker-images:
    name: Build all docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build prod images
        run: cd src && docker compose build -f docker-compose.yml

      - name: Build dev images
        run: cd src && docker compose build -f docker-compose.dev.yml

  lint-wallet:
    name: Build and lint wallet service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint frontend
        run: npm ci && npm run ci-dry-run
        working-directory: ./src/wallet-frontend

      - name: Lint backend
        run: uvx flake8 . --show-source --statistics
        working-directory: ./src/wallet-backend/src
